export const getWeatherIcon = (code) => ({
    '01d': '☀️  Clear sky',
    '01n': '🌙  Clear sky',
    '02d': '🌤️  Few clouds',
    '02n': '🌤️  Few clouds',
    '03d': '☁️  Scattered clouds',
    '03n': '☁️  Scattered clouds',
    '04d': '☁️  Broken clouds',
    '04n': '☁️  Broken clouds',
    '09d': '🌧️  Shower rain',
    '09n': '🌧️  Shower rain',
    '10d': '🌦️  Rain',
    '10n': '🌧️  Rain',
    '11d': '⛈️  Thunderstorm',
    '11n': '⛈️  Thunderstorm',
    '13d': '❄️  Snow',
    '13n': '❄️  Snow',
    '50d': '🌫️  Mist',
    '50n': '🌫️  Mist',
})[code] || '🌍  Weather';